name: Jotter Docker Builds

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build Jotter
        run: |
          docker build ./src -t abzali8806/jotter:1.0.0
      - name: docker push
        run: |
          docker push abzali8806/jotter:1.0.0
          
